---
title: "Untitled"
<<<<<<< HEAD
author: "Becky", "Jianhao Yan","Yifu Dong","Megha Pandit"
=======
author: "Becky"
>>>>>>> f08771287e4814f848c361a58da3da1bb12c7ee2
date: "11/26/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
<<<<<<< HEAD
library(benford.analysis).
data(census.2000_2010).
=======
library(benford.analysis)
data(census.2000_2010)
>>>>>>> f08771287e4814f848c361a58da3da1bb12c7ee2
bfd.cp <- benford(census.2000_2010$pop.2000,1)
plot(bfd.cp, except=c("mantissa", "chi square", "abs diff", "second order"), multiple = T)
```

```{r}
MAD(bfd.cp)
duplicatesTable(bfd.cp)
suspects <- getSuspects(bfd.cp, census.2000_2010)
suspects
```

```{r}
library(BenfordTests)
<<<<<<< HEAD
library(benford.analysis)
data(census.2000_2010)
bfd.cp <- benford(census.2000_2010$pop.2000,1)
plot(bfd.cp, except=c("mantissa", "chi square", "abs diff", "second order"), multiple = T)

```

```{r}
MAD(bfd.cp)
duplicatesTable(bfd.cp)
suspects <- getSuspects(bfd.cp, census.2000_2010)
suspects

```

=======

```
>>>>>>> f08771287e4814f848c361a58da3da1bb12c7ee2
